version: '3.4'
services:
  app:
    image: registry.gitlab.com/jerejunttila/jela-react:stable
    ports:
      - 8085:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY
    restart: always
