version: '3.4'
services:
  app:
    image: ghcr.io/arawnik/jela-react:main
    ports:
      - 8085:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY
    restart: always
