services:
  app:
    image: jela-react-compose
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8084:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY
    env_file: .env.local
