name: Build and Push Docker Image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  workflow_dispatch:  # Allow manual trigger with inputs
    inputs:
      tag:
        description: 'Docker image tag (e.g., stable)'
        required: false
        default: 'latest'
      api-base-url:
        description: 'API base URL'
        required: false
        default: 'https://jerejunttila.fi/api'
      public-recaptcha-key:
        description: 'Public recaptcha site key'
        required: false
        default: '6LctfJ0UAAAAAA6LWsCyDjF_a4xcQqZzVKeanAhd'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set Docker tag and environment variables
    - name: Set environment variables
      id: env
      run: |
        echo "tag=${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_ENV
        echo "api_base_url=${{ github.event.inputs.api-base-url }}" >> $GITHUB_ENV
        echo "public_recaptcha_key=${{ github.event.inputs.public-recaptcha-key }}" >> $GITHUB_ENV

    # Step 3: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/arawnik/jela-react:${{ github.ref_name }}
        build-args: |
          NEXT_PUBLIC_API_BASE_URL=${{ github.event.inputs.api-base-url }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ github.event.inputs.public-recaptcha-key }}
